#Q. What is this repo all about?
#A. A Repository for my coding/scripting challenges in Code Fellows Ops 201 course.

#Q. Why are you learning these skills?
#A. For basic understanding of coding and scripting gives a basis for understanding to read and write in a functional manner. As I progress in cybersecurity training and experience, It would be great to automate more tools in this way. 

#Q. What fundamental concepts did you learn in Ops 201?
#Ops 201 taught me:
# * Fundamental IT operations such as troubleshooting for computer hardware and software, with associated tools.
#  * Different operating systems, particularly Linux and Windows
#  * Basic coding and writing scripts in bash and powershell, to include operations such as loops, variables, functions and other coding tools
#  * Introduction to some topics that will be learned in more detail later, such as networking and cybersecurity

#Q. What was your favorite Ops Challenge assignment and why?
#A. '; 

#How can these examples of shell scripting be applied to the workplace?

#What scripts would you continue to improve if you had the time?

#What aspect of your shell scripting skillset do you hope to improve next?